spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.178.230.36:3306/User_center
    username: wth
    password: wth

  session:
    timeout: 86400